### ISSUE TITLE
Folder install eclipse-jee in MAC

### ISSUE THREAD

**Issue by t-bonatti** [caarlos0/fast-eclipse#14]
When I installed eclipse I found this error:

```
TASK [ansible-role-eclipse : file] ***********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /Applications/Eclipse.app/Contents/MacOS/eclipse", "path": "/usr/local/bin/eclipse", "src": "/Applications/Eclipse.app/Contents/MacOS/eclipse", "state": "absent"}
	to retry, use: --limit @/Users/bonatti/Code/ansible-role-eclipse/tests/test.retry
```

In my MAC, the folder has installed is:

```
/Applications/Eclipse JEE.app
```
<img width="530" alt="captura de tela 2017-05-01 as 10 17 15" src="https://cloud.githubusercontent.com/assets/1936245/25580454/7a808516-2e57-11e7-9887-931fe7b3a0fe.png">

I changed the variable [eclipse_folder](https://github.com/caarlos0/ansible-role-eclipse/blob/master/tasks/install_MacOSX.yml#L2)  and the installation is successful.

**Is it a bug or my MAC is special?**

### Infos:

![image](https://cloud.githubusercontent.com/assets/1936245/25580487/c97c7846-2e57-11e7-9703-4b2e9e1470a0.png)

![image](https://cloud.githubusercontent.com/assets/1936245/25580504/e7407d8c-2e57-11e7-8801-577133469db3.png)

**Comment by caarlos0** [comment]
bug, fixed in 694df33
